function [I,I1,I2,rW1,psnrnoiseim,psnrnoisewm, corcoeffwm,rW2,psnrnoiseim1,psnrnoisewm1, corcoeffwm1,rW3,psnrnoiseim2,psnrnoisewm2, corcoeffwm2] = noise(images,WM)
k=0.2;
obj = VideoReader('watermarkedVideo.avi');
video = read(obj);
nFrames = size(video,4);

parfor i = 1:nFrames
    I(:,:,i) = imnoise(video(:,:,i),'gaussian');
    I1(:,:,i)= imnoise(video(:,:,i),'poisson');
    I2(:,:,i)= imnoise(video(:,:,i),'salt & pepper');
end

for j=1:nFrames
    [eA1,eH1,eV1,eD1] = dwt2(I(:,:,j),'haar');
    alleA1(:,:,j) = eA1;
    alleH1(:,:,j) = eH1;
    alleV1(:,:,j) = eV1;
    alleD1(:,:,j) = eD1;
    [eU1,eS1,~] = svd(alleD1(:,:,j));
    alleU1(:,:,j) = eU1;
    alleS1(:,:,j) = eS1;
    [cA,cH,cV,cD] = dwt2(images{j},'haar');
    allcA(:,:,j) = cA;
    allcH(:,:,j) = cH;
    allcV(:,:,j) = cV;
    allcD(:,:,j) = cD;
    [U,S,V] = svd(allcD(:,:,j));
    allU(:,:,j) = U;
    allS(:,:,j) = S;
    allV(:,:,j) = V;
    W = imresize(WM,[360,204]);
    W = rgb2gray(W);
    [waA,waH,waV,waD] = dwt2(W,'haar');
    [wU,wS,wV] = svd(waD);
    s(:,:,j) = (wS - allS(:,:,j))/k;
    wDd(:,:,j) = wU*s(:,:,j)*wV';
    rW1(:,:,j) = idwt2(waA,waH,waV,wDd(:,:,j),'haar');
    rW1(:,:,j) = uint8(rW1(:,:,j));
    psnrnoiseim = psnr(uint8(I(:,:,j)),images{j});
    psnrnoisewm = psnr(uint8(rW1(:,:,1)),W);
    corcoeffwm = corr2(uint8(rW1(:,:,1)),W); 
    
    [eA2,eH2,eV2,eD2] = dwt2(I1(:,:,j),'haar');
    alleA2(:,:,j) = eA2;
    alleH2(:,:,j) = eH2;
    alleV2(:,:,j) = eV2;
    alleD2(:,:,j) = eD2;
    [eU2,eS2,~] = svd(alleD2(:,:,j));
    alleU2(:,:,j) = eU2;
    alleS2(:,:,j) = eS2;
    [cA2,cH2,cV2,cD2] = dwt2(images{j},'haar');
    allcA2(:,:,j) = cA2;
    allcH2(:,:,j) = cH2;
    allcV2(:,:,j) = cV2;
    allcD2(:,:,j) = cD2;
    [U2,S2,V2] = svd(allcD2(:,:,j));
    allU2(:,:,j) = U2;
    allS2(:,:,j) = S2;
    allV2(:,:,j) = V2;
%     W = imresize(WM,[360,204]);
%     W = rgb2gray(W);
%     [waA,waH,waV,waD] = dwt2(W,'haar');
%     [wU,wS,wV] = svd(waD);
    s2(:,:,j) = (wS - allS2(:,:,j))/k;
    wDd2(:,:,j) = wU*s2(:,:,j)*wV';
    rW2(:,:,j) = idwt2(waA,waH,waV,wDd2(:,:,j),'haar');
    rW2(:,:,j) = uint8(rW2(:,:,j));
    psnrnoiseim1 = psnr(uint8(I1(:,:,j)),images{j});
    psnrnoisewm1 = psnr(uint8(rW2(:,:,1)),W);
    corcoeffwm1 = corr2(uint8(rW2(:,:,1)),W); 
    
     [eA3,eH3,eV3,eD3] = dwt2(I2(:,:,j),'haar');
    alleA3(:,:,j) = eA3;
    alleH3(:,:,j) = eH3;
    alleV3(:,:,j) = eV3;
    alleD3(:,:,j) = eD3;
    [eU3,eS3,~] = svd(alleD3(:,:,j));
    alleU3(:,:,j) = eU3;
    alleS3(:,:,j) = eS3;
    [cA3,cH3,cV3,cD3] = dwt2(images{j},'haar');
    allcA3(:,:,j) = cA3;
    allcH3(:,:,j) = cH3;
    allcV3(:,:,j) = cV3;
    allcD3(:,:,j) = cD3;
    [U3,S3,V3] = svd(allcD3(:,:,j));
    allU3(:,:,j) = U3;
    allS3(:,:,j) = S3;
    allV3(:,:,j) = V3;
%     W = imresize(WM,[360,204]);
%     W = rgb2gray(W);
%     [waA,waH,waV,waD] = dwt2(W,'haar');
%     [wU,wS,wV] = svd(waD);
    s3(:,:,j) = (wS - allS3(:,:,j))/k;
    wDd3(:,:,j) = wU*s3(:,:,j)*wV';
    rW3(:,:,j) = idwt2(waA,waH,waV,wDd3(:,:,j),'haar');
    rW3(:,:,j) = uint8(rW3(:,:,j));
    psnrnoiseim2 = psnr(uint8(I2(:,:,j)),images{j});
    psnrnoisewm2 = psnr(uint8(rW3(:,:,1)),W);
    corcoeffwm2 = corr2(uint8(rW3(:,:,1)),W);   
end

end
